// <auto-generated />
using System;
using GroupService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GroupService.Infrastructure.Migrations
{
    [DbContext(typeof(GroupContext))]
    [Migration("20260523151003_add_start_and_end_time_to_event_projection")]
    partial class add_start_and_end_time_to_event_projection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GroupService.Domain.Entities.EventProjection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.ToTable("EventProjections");
                });

            modelBuilder.Entity("GroupService.Domain.Entities.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CountStudents")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("GroupService.Domain.Entities.GroupEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("ActualCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("EventProjectionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<int>("PlannedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Planned");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("EventProjectionId", "GroupId")
                        .IsUnique();

                    b.ToTable("GroupEvents");
                });

            modelBuilder.Entity("GroupService.Domain.Entities.GroupEvent", b =>
                {
                    b.HasOne("GroupService.Domain.Entities.EventProjection", "EventProjection")
                        .WithMany("GroupEvents")
                        .HasForeignKey("EventProjectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GroupService.Domain.Entities.Group", "Group")
                        .WithMany("GroupEvents")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventProjection");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("GroupService.Domain.Entities.EventProjection", b =>
                {
                    b.Navigation("GroupEvents");
                });

            modelBuilder.Entity("GroupService.Domain.Entities.Group", b =>
                {
                    b.Navigation("GroupEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
